# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e6ddccc1092262c6f9b3c1f08077508c"
name = "testing-express-app"
handle = "testing-express-app-3"
application_url = "https://solved-chi-focused-wrong.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://solved-chi-focused-wrong.trycloudflare.com/auth/callback", "https://solved-chi-focused-wrong.trycloudflare.com/auth/shopify/callback", "https://solved-chi-focused-wrong.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
